version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=loki-messenger
    ports:
      - '5432:5432'
    volumes:
      - ./backend-go/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend-go
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/loki-messenger
      - JWT_SECRET=your-secret-key